name: Pull Request
on:
  pull_request:
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic PowerShell syntax check
        shell: pwsh
        run: Get-ChildItem -Recurse -Filter *.ps1 | % { Write-Host "Checking $($_.FullName)"; powershell -NoProfile -Command "Set-StrictMode -Version Latest; [void](Get-Content '$_' -Raw)" }